name: security_311_admin
description: "Admin dashboard for 3:11 Security application."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.10.3
  flutter_dotenv: ^6.0.0
  provider: ^6.1.5
  logger: ^2.6.2
  intl: ^0.20.2
  google_fonts: ^6.3.2
  flutter_local_notifications: ^19.5.0
  shared_preferences: ^2.5.3
  connectivity_plus: ^7.0.0
  shimmer: ^3.0.0
  fl_chart: ^1.1.1
  flutter_svg: ^2.2.3
  sentry_flutter: ^9.8.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.2
  path_provider: ^2.1.4
  path: ^1.9.0
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  permission_handler: ^11.3.1
  web: ^1.1.1
  google_maps_flutter: ^2.10.0
  google_maps_flutter_web: ^0.5.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
